import { ThemeProvider } from "@/components/theme-provider"
import AuthProvider from "@/context/AuthProvider"
import type { Metadata } from "next"
import "./globals.css"
import { Providers } from "@/redux/provider"
import { store } from "@/redux/store"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <html
        lang="en"
        suppressHydrationWarning
      >
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AuthProvider>
              <Providers>{children}</Providers>
            </AuthProvider>
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
